---
- name: Install MySQL Server
  hosts: all
  become: yes  
  gather_facts: true  

  tasks:
    - name: Update apt package cache 
      apt:
        update_cache: yes
      when: ansible_distribution == 'Ubuntu'

    - name: Install PyMySQL
      pip:
        name: pymysql
        state: present 

    - name: Install MySQL Server
      package:
        name: mysql-server 
        state: present  

    - name: Start MySQL service
      service:
        name: mysql 
        state: started

    - name: Enable MySQL service at boot
      service:
        name: mysql
        enabled: yes
    
    - name: Create database user altschool
      mysql_user: user=altschool  password=altschool priv=*.*:ALL state=present
#      no_log: yes

    - name: Create database altschool
      mysql_db:
        login_unix_socket: /var/run/mysqld/mysqld.sock     
        name: altschool 
        state: present

    - name: Create a Table reg
      command: mysql -u altschool -paltschool -e 'CREATE TABLE reg (name varchar(30), email varchar(30));' altschool




